### ISSUE TITLE
Supeabase example doesn't work

### ISSUE THREAD

**Issue by beorn** [maxnowack/signaldb#984]
Hi,

When doing any modification to the Supabase example (even the one publicly hosted) I get "Error: Item with ID blablabla not found", e.g.,

```console
286-4225366261efa118.js:1 persistence.error Error: Item with ID 344 not found
    at 279.62a5867e0a3ecd8d.js:1:182023
    at Array.forEach (<anonymous>)
    at Object.save (279.62a5867e0a3ecd8d.js:1:181957)
    at Object.save (279.62a5867e0a3ecd8d.js:1:183197)
    at o (279.62a5867e0a3ecd8d.js:1:175716)
    at re.<anonymous> (279.62a5867e0a3ecd8d.js:1:176069)
    at re.emit (279.62a5867e0a3ecd8d.js:1:132802)
    at re.updateOne (279.62a5867e0a3ecd8d.js:1:180263)
    at onChange (50.0146f0139b5ca676.js:1:61709)
    at Object.a_ (1dd3208c-7ceafcdacb3835b2.js:1:72142)
```

On a related note, could you perhaps also include some info on the the Supabase setup that goes with this example (schema, RLS setup)?

**Comment by beorn** [comment]
Thx! :)
